---
title: "R Notebook"
output: html_notebook
---

# Data Cleaning BVG 
```{r}
library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(stringr)
library(leaflet)


```


## BVG data cleaning
```{r}
df.bvg.requests <- fread('BVG/anfragen_20170718.csv')
df.bvg.requests <- na.omit(df.bvg.requests, cols='START_NAME')
df.bvg.requests$START_ID<- as.character(df.bvg.requests$START_ID)
df.bvg.requests$ZIEL_NR<- as.character(df.bvg.requests$ZIEL_NR)
df.bvg.stops.geo <- fread('BVG/gtfs/stops.txt') 

# gtfs Berlin Hbhf _ 900000003201 / requests : 9003201
df.bvg.stops.geo <- distinct(df.bvg.stops.geo,parent_station, .keep_all= TRUE)
df.bvg.stops.geo <- df.bvg.stops.geo %>% filter(!is.na(parent_station))
df.bvg.stops.geo <- df.bvg.stops.geo %>% mutate('START_ID'=str_replace_all(parent_station, pattern = "00000", replacement = "")) 

df.bvg.stops.geo <- distinct(df.bvg.stops.geo)
df.bvg.stops.geo.start <- df.bvg.stops.geo %>% select(START_ID,'stop_lat_start'=stop_lat,'stop_lon_start'=stop_lon)
df.bvg.stops.geo.end <- df.bvg.stops.geo %>% select(START_ID,'stop_lat_end'=stop_lat,'stop_lon_end'=stop_lon)

df.merged <- merge(df.bvg.requests,df.bvg.stops.geo.start,by='START_ID',all.x=T,suffixes = c('_requests','_start')) 
df.merged <- merge(df.merged,df.bvg.stops.geo.end,by.x='ZIEL_NR',by.y='START_ID',all.x=T,suffixes = c('_requests','_end'))
df.merged <- df.merged %>% mutate(START_X=ifelse(is.na(START_X),stop_lat_start,START_X))
df.merged <- df.merged %>% mutate(START_Y=ifelse(is.na(START_Y),stop_lon_start,START_Y))

df.merged <- df.merged %>% mutate(ZIEL_X=ifelse(is.na(ZIEL_X),stop_lat_end,ZIEL_X))
df.merged <- df.merged %>% mutate(ZIEL_Y=ifelse(is.na(ZIEL_Y),stop_lon_end,ZIEL_Y))
# create a df of start_id that are not unknown (i.e no start lat/lon):

df.merged$request_datetime <- dmy_hm(str_c(df.merged$ANFRAGE_DATUM,df.merged$ANFRAGE_ZEIT))
df.merged$ANFRAGE_DATUM<- dmy(df.merged$ANFRAGE_DATUM)
df.merged$request_datetime_rounded <- round_date(df.merged$request_datetime, unit = "hour",
  week_start = getOption("lubridate.week.start", 7))

df.merged$request_time_rounded <- hour(df.merged$request_datetime_rounded)

df.merged <- df.merged %>% filter(ANFRAGE_DATUM>'2017-07-16' & ANFRAGE_DATUM<'2017-07-19')
df.merged$start_lat_lon <- str_c(df.merged$START_X,'_',df.merged$START_Y)
df.merged$end_lat_lon <- str_c(df.merged$ZIEL_X,'_',df.merged$ZIEL_Y)


df.flat <- df.merged %>% group_by(request_datetime_rounded, start_lat_lon,end_lat_lon)%>% summarise(total_queries=n())

df.flat$from_lat<- str_extract(df.flat$start_lat_lon, "[^_]+") %>% as.numeric()
df.flat$from_lng<- str_extract(df.flat$start_lat_lon, "[^_]+$") %>% as.numeric()


df.flat$to_lat<- str_extract(df.flat$end_lat_lon, "[^_]+") %>% as.numeric()
df.flat$to_lng<- str_extract(df.flat$end_lat_lon, "[^_]+$") %>% as.numeric()

df.flat$from_name <- df.flat$start_lat_lon
df.flat$to_name <- df.flat$end_lat_lon

# swap wrong lat/lon :
df.flat <- df.flat %>% na.omit(from_lat)
index.nok <- df.flat$from_lat<=30
df.flat[index.nok, c("from_lng", "from_lat")] <- df.flat[index.nok, c("from_lat", "from_lng")]

df.flat <- df.flat %>% na.omit(to_lat)
index.nok <- df.flat$to_lat<=30
df.flat[index.nok, c("to_lng", "to_lat")] <- df.flat[index.nok, c("to_lat", "to_lng")]

write.csv(df.flat,'bvg_flat.csv')


```

## convert to GEOJSON
```{r}
#Load libraries
library(rgdal)

#dataMap is a dataframe with coordinates on cols 11 (LATITUDE) and 12 (LONGITUDE)
#Transfor coordinates to numeric
df.test$LATITUDE  <- as.numeric(df.test$LATITUDE)
dataMap$LONGITUDE  <- as.numeric(dataMap$LONGITUDE)
dataMap.SP  <- SpatialPointsDataFrame(dataMap[,c(12,11)],dataMap[,-c(12,11)])
str(dataMap.SP) # Now is class SpatialPointsDataFrame

#Write as geojson
writeOGR(dataMap.SP, 'dataMap.geojson','dataMap', driver='GeoJSON')
```


```{r}
groupy.start <- df.merged %>% group_by(request_datetime_rounded, start_lat_lon)%>% summarise(total_date=n())
groupy.end  <-  df.merged %>% group_by(request_datetime_rounded, end_lat_lon)%>% summarise(total_date=n())
groupy.start$lat<- str_extract(groupy.start$start_lat_lon, "[^_]+") %>% as.numeric()
groupy.start$lon<- str_extract(groupy.start$start_lat_lon, "[^_]+$") %>% as.numeric()

groupy.end$lat<- str_extract(groupy.end$end_lat_lon, "[^_]+")
groupy.end$lon<- str_extract(groupy.end$end_lat_lon, "[^_]+$")


# swap wrong lat/lon :
groupy.start <- groupy.start %>% na.omit(lat)
index.nok <- groupy.start$lat<=30
groupy.start[index.nok, c("lon", "lat")] <- groupy.start[index.nok, c("lat", "lon")]

groupy.end <- groupy.end %>% na.omit(lat)
index.nok <- groupy.end$lat<=30
groupy.end[index.nok, c("lon", "lat")] <- groupy.end[index.nok, c("lat", "lon")]


# merge both Start and End
groupy.merged <- merge(groupy.start,groupy.end,by=c('lat','lon','request_datetime_rounded'))

write.csv(groupy.start,'BVG_start_points.csv')
write.csv(groupy.end,'BVG_end_points.csv')

```

